services:
  static-site:
    build: .
    container_name: moongroup_site
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=moongroup.vuvandinh.id.vn
      - LETSENCRYPT_HOST=moongroup.vuvandinh.id.vn
      - LETSENCRYPT_EMAIL=vuvandinh203@gmail.com
    networks:
      - webproxy

networks:
  webproxy:
    external: true
